version: '3'

services:
  web:
    image: php:8.1-apache
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: Thingsafe
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mysql:8.0.32
    ports:
      - "3307:3306" #normalmente essa parte é: "3306:3306"
    environment:
      MYSQL_DATABASE: Thingsafe
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
